"""
br_bonds/_schedules.py
──────────────────────
Cashflow schedule builders for Brazilian government bonds (ANBIMA BUS/252).

Public functions
----------------
price_from_schedule(ytm, cf_du, cashflows)
    Scalar pricing from a pre-built schedule (any bond type).

bond_cashflow_schedule(du_mat, coupon, face, freq, ...)
    LTN / NTN-F coupon schedule.
    Zero-coupon (coupon=0) → single cash flow at du_mat.
    When coupon_dates + calendar supplied → uses actual ANBIMA Jan 1 / Jul 1
    dates (with 5-day buffer for holiday adjustment); otherwise uniform 126-bday spacing.

ntnb_cashflow_schedule(date, mat, cal, coupon, face, freq)
    NTN-B / NTN-B-P coupon schedule.
    Coupons on Jan 15 / Jul 15 (or May 15 / Nov 15 etc.) — generated by
    stepping back from unadjusted maturity in 6-month intervals.

ntnb_coupon_dates(start, end, cal)
    Generate the full ANBIMA-adjusted NTN-B semiannual coupon date grid.

ntnb_coupon_dates_for_bond(maturity, start, end, cal)
    Coupon dates for a specific NTN-B bond aligned to its maturity month/day.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from bizdays import Calendar


# ── standalone pricing from schedule ─────────────────────────────────────────

def price_from_schedule(
    ytm: float,
    cf_du: np.ndarray,
    cashflows: np.ndarray,
) -> float:
    """
    Price a bond from its cashflow schedule under BUS/252 compounding.

    Parameters
    ----------
    ytm       : annual yield (decimal), ANBIMA BUS/252
    cf_du     : business days to each cash flow
    cashflows : corresponding cash flow amounts

    Returns
    -------
    float — sum of discounted cash flows
    """
    return float(np.sum(cashflows / (1.0 + ytm) ** (cf_du / 252.0)))


# ── LTN / NTN-F schedule ──────────────────────────────────────────────────────

def bond_cashflow_schedule(
    du_mat: float,
    coupon: float,
    face: float = 1000.0,
    freq: int = 2,
    date_np: np.datetime64 | None = None,
    mat_np:  np.datetime64 | None = None,
    cal: Calendar | None = None,
    coupon_dates: np.ndarray | None = None,   # sorted datetime64[D]
) -> tuple[np.ndarray, np.ndarray]:
    """
    Cashflow schedule (cf_du, cashflows) for an LTN or NTN-F.

    If coupon == 0: single cash flow at du_mat (LTN / zero-coupon).
    If coupon_dates + date_np + mat_np + cal are all provided: uses actual
    ANBIMA payment dates (Jan 1 / Jul 1 adjusted), including 5-day buffer
    to capture the holiday-adjusted maturity coupon.
    Otherwise: uniform spacing of 252//freq business days.
    """
    c = face * ((1.0 + coupon) ** (1.0 / freq) - 1.0) if coupon > 0 else 0.0

    if coupon == 0.0:
        return np.array([du_mat]), np.array([face])

    if (coupon_dates is not None and date_np is not None
            and mat_np is not None and cal is not None):
        mat_d64 = (mat_np.astype('datetime64[D]')
                   if mat_np.dtype != np.dtype('datetime64[D]') else mat_np)
        mat_buf = mat_d64 + np.timedelta64(5, 'D')
        mask    = (coupon_dates > date_np) & (coupon_dates <= mat_buf)
        cpn_dt  = coupon_dates[mask]
        if len(cpn_dt) == 0:
            cf_du = np.array([du_mat])
        else:
            cf_du = np.array(
                [cal.bizdays(
                    pd.Timestamp(date_np.astype('datetime64[ms]').astype(object)),
                    pd.Timestamp(str(d)),
                 ) for d in cpn_dt],
                dtype=np.float64,
            )
            cf_du[-1] = du_mat
    else:
        step  = 252 // freq
        cf_du = np.arange(step, du_mat + step, step, dtype=np.float64)
        cf_du = cf_du[cf_du <= du_mat + 0.5]
        if len(cf_du) == 0 or cf_du[-1] < du_mat:
            cf_du = np.append(cf_du, du_mat)

    cashflows      = np.full(len(cf_du), c)
    cashflows[-1] += face
    return cf_du, cashflows


# ── NTN-B schedule ────────────────────────────────────────────────────────────

def ntnb_cashflow_schedule(
    date: pd.Timestamp,
    mat:  pd.Timestamp,
    cal:  Calendar,
    coupon: float,
    face: float = 100.0,
    freq: int   = 2,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Exact NTN-B coupon schedule for a single bond.

    NTN-B coupons fall on the same day-of-month as maturity, every
    ``12//freq`` months (e.g., Aug 15 maturity → coupons on Feb 15 / Aug 15).
    Each date is adjusted to the next business day if needed.

    Parameters
    ----------
    date   : pricing / settlement date
    mat    : bond maturity date (unadjusted OK — adjustment applied below)
    cal    : ANBIMA calendar (used for bizday count and adjustment)
    coupon : annual real coupon rate (decimal); 0.0 for NTN-B Principal
    face   : face value in cotação space (default 100)
    freq   : payments per year (default 2)

    Returns
    -------
    (cf_du, cashflows) — business days and cash flows aligned to date.
    """
    step_months = 12 // freq
    date = pd.Timestamp(date)

    # Adjust maturity to next business day (ANBIMA convention)
    mat_adj = pd.Timestamp(cal.adjust_next(mat) if not cal.isbizday(mat) else mat)

    if coupon == 0.0:
        du_mat = float(cal.bizdays(date, mat_adj))
        return np.array([du_mat]), np.array([face])

    # Step back from maturity collecting one date <= date (needed for period length)
    unadj: list[pd.Timestamp] = []
    d = mat
    while d > date:
        unadj.append(d)
        d = d - pd.DateOffset(months=step_months)
    unadj.append(d)   # one date on or before pricing date
    unadj.sort()

    # Adjust every date to next business day
    adj = [
        pd.Timestamp(cal.adjust_next(d) if not cal.isbizday(d) else d)
        for d in unadj
    ]

    # Collect future coupon dates (strictly after pricing date)
    future_dates = [d for d in adj if d > date]

    if not future_dates:
        du_mat = float(cal.bizdays(date, mat_adj))
        return np.array([du_mat]), np.array([face])

    # Fixed semi-annual coupon (ANBIMA convention): C = face × [(1+coupon)^(1/freq) − 1]
    c = face * ((1.0 + coupon) ** (1.0 / freq) - 1.0)

    cf_du     = np.array([float(cal.bizdays(date, d)) for d in future_dates],
                         dtype=np.float64)
    cashflows = np.full(len(future_dates), c, dtype=np.float64)
    cashflows[-1] += face

    return cf_du, cashflows


# ── NTN-B coupon date grid ─────────────────────────────────────────────────────

def ntnb_coupon_dates(
    start: str = '2000-01-15',
    end:   str = '2060-07-15',
    cal: Calendar | None = None,
) -> pd.DatetimeIndex:
    """
    Generate ANBIMA-adjusted NTN-B semiannual coupon dates (Jan 15 / Jul 15).

    Parameters
    ----------
    start : first coupon date to include (default '2000-01-15')
    end   : last coupon date to include  (default '2060-07-15')
    cal   : bizdays Calendar — if provided, non-business days are moved
            to the next business day (ANBIMA convention).

    Returns
    -------
    pd.DatetimeIndex sorted ascending.
    """
    # Build Jan 1 / Jul 1 grid, shift +14 days → Jan 15 / Jul 15
    raw = pd.date_range(
        start='1999-07-01',
        end=pd.Timestamp(end) + pd.DateOffset(days=30),
        freq='6MS',
    ) + pd.DateOffset(days=14)

    raw = raw[(raw >= pd.Timestamp(start)) & (raw <= pd.Timestamp(end))]

    if cal is not None:
        raw = pd.DatetimeIndex([
            cal.adjust_next(d) if not cal.isbizday(d) else d
            for d in raw
        ])

    return raw.sort_values()


def ntnb_coupon_dates_for_bond(
    maturity: pd.Timestamp,
    start:    pd.Timestamp,
    end:      pd.Timestamp,
    cal:      Calendar,
) -> list[pd.Timestamp]:
    """
    Coupon dates for a specific NTN-B bond (6-month grid aligned to
    maturity day-of-month), ANBIMA-adjusted, in [start, end].

    Parameters
    ----------
    maturity : bond maturity date (unadjusted)
    start    : window start (inclusive)
    end      : window end   (inclusive)
    cal      : ANBIMA Calendar

    Returns
    -------
    Sorted list of adjusted coupon Timestamps within [start, end].
    """
    dates: list[pd.Timestamp] = []
    d = maturity
    while d >= start - pd.DateOffset(months=6):
        adj = pd.Timestamp(cal.adjust_next(d) if not cal.isbizday(d) else d)
        if start <= adj <= end:
            dates.append(adj)
        d = d - pd.DateOffset(months=6)
    return sorted(set(dates))
